import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'normalize.css';
import "../globals.scss";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { signInPath } from "@/paths";
import { Aside } from "@/components/Aside";
import style from "./layout.module.scss";
import { getNumbersTrucks } from "@/features/trucks/queries/getNumbersTrucks";
import { getNumbersTrailers } from "@/features/trailers/queries/getNumbersTrailers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  if (!session) redirect(signInPath());

  const trucks = await getNumbersTrucks();
  const trailers = await getNumbersTrailers();
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={style.layoutContainer}>
          <Aside trucks={trucks} trailers={trailers} />
          <main>{children}</main>
        </div>
        
      </body>
    </html>
  );
}
