import { auth } from "@/lib/auth";
import StoreProvider from "../(root)/StoreProvider"
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const session = await auth();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <StoreProvider>
          <body>{children}</body>
        </StoreProvider>
      </SessionProvider>
    </html>
  )
}
